[package]
name = "rust_primer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3-ffi = "0.19.2"
yubikey = "0.8.0"
